#!/usr/bin/env python2
# -*- encoding: utf-8 -*-

from kobunsupport import load_config, handshake, read_line, write_line, parse_prefix

import random

handshake("ops for all")

config = load_config()

while True:
  server, prefix, command, args = read_line()

  if command.lower() == "privmsg":
    nick, user, host = parse_prefix(prefix)
    target, msg = args

    parts = msg.split(' ', 1)

    if parts[0] == '!op':
      write_line(server, "MODE", [target, "+o", parts[1].strip()])
